### PR TITLE
merge matone forest changes to master

### PR DESCRIPTION
**Pull request by huesca12**
Review changes based on Dr. Matone's recommendations for merging into the main branch.

### CODE REVIEW

**Comment by huesca12** [comment]
So just a note on roughly what I think needs to be reviewed.

1. The 10/90 hard-coded split should be scrapped in favor of a user query
2. Some edits were made to the initial csv loading that need to be checked for compliance (i.e. preserve original forest.py setup)
3. User should be queried about if they want to investigate based on Hanford/Livingston

Feel free to suggest any other changes you think are relevant

**Comment by huesca12** [comment]
An additional note this pull request is only to be marked as ready for review when changes have been shared with everbody

**Comment by YulkyTulky** [comment]
> 1. The 10/90 hard-coded split should be scrapped in favor of a user query

Absolutely, we do not want to limit this script to one specific use case. We should add queries for what dataset to use, what percentage of it to use, and what dataset + percentage to compare it against. Also queries on H1 vs L1 and confidence values (unless we want to just accept a hardline of using all data vs only high confidence data) ... Also, in the statistic function, I am confused how there could ever be a scenario in which you need the final else statement; just get rid of it ... Lastly, I think there is a typo on the last line, it should be "results.csv" I assume? Or use some better naming convention that describes the output based on the datasets/percentages/interferometer/etc. that was chosen

**Comment by huesca12** [comment]
> > 1. The 10/90 hard-coded split should be scrapped in favor of a user query
> 
> 
> 
> Absolutely, we do not want to limit this script to one specific use case. We should add queries for what dataset to use, what percentage of it to use, and what dataset + percentage to compare it against. Also queries on H1 vs L1 and confidence values (unless we want to just accept a hardline of using all data vs only high confidence data) ... Also, in the statistic function, I am confused how there could ever be a scenario in which you need the final else statement; just get rid of it ... Lastly, I think there is a typo on the last line, it should be "results.csv" I assume? Or use some better naming convention that describes the output based on the datasets/percentages/interferometer/etc. that was chosen

@YulkyTulky 

Sounds good we can start writing commits to this branch until we have something we feel good on moving on with. I also spoke with Dr. Matone recently and it seems that the performance we’ve gotten with random forest is satisfactory for starting to work on finalizing our code. So we can consider work on this branch as work towards producing a final “release” version to present to Dr. Marka.

**Pull request closed without merging**
